### ISSUE TITLE
Erreur lors de la sauvegarde des informations d'une personne 

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/vertigo-demo-api#6]
![image](https://cloud.githubusercontent.com/assets/3300779/14742096/c2a6ae8a-089a-11e6-89cd-d7c697603217.png)

2016-04-22 14:51:25 ERROR ExceptionWebServiceHandlerPlugin:98 - Internal Server Error
io.vertigo.lang.VSystemException: Aucune méthode trouvée pour l'attribut 'birthPlace' sur classe 'io.vertigo.pandora.domain.persons.Person'
	at io.vertigo.util.BeanUtil.getPropertyDescriptor(BeanUtil.java:122)
	at io.vertigo.util.BeanUtil.getValue(BeanUtil.java:58)
	at io.vertigo.dynamo.domain.metamodel.DataAccessor.getValue(DataAccessor.java:81)
	
Il n' y  a pas de getter pour le champ 'birthPlace' dans la classe Person.

**Comment by JoanaDalmeida** [comment]
cc @Tommass

**Comment by JoanaDalmeida** [comment]
Correction faite en local pour déployer la démo.
